wandb_version: 1

batch_size:
  value: 4494
bidir:
  value: false
customLoss:
  value: false
dropout:
  value: 0.25598277390955126
initial_lr:
  value: 0.02433429947052071
numFC:
  value: 4
numRNN:
  value: 4
remove_mean:
  value: false
replace_nan_by_min:
  value: true
sizeFC:
  value: 40
sizeRNN:
  value: 29
weight_decay:
  value: 0.0001192802689036645
weighted:
  value: true
whichDataset:
  value: ratio
whichDisplacement:
  value: true
whichFFT:
  value: true
xyDisplacement:
  value: true
