wandb_version: 1

batch_size:
  value: 319
bidir:
  value: true
customLoss:
  value: false
dropout:
  value: 0.3993100501091661
initial_lr:
  value: 0.055602208089510795
numFC:
  value: 3
numRNN:
  value: 2
remove_mean:
  value: false
replace_nan_by_min:
  value: false
sizeFC:
  value: 29
sizeRNN:
  value: 77
weight_decay:
  value: 0.007922000283555454
weighted:
  value: false
whichDataset:
  value: indiv
whichDisplacement:
  value: false
whichFFT:
  value: false
xyDisplacement:
  value: false
